---
name: "Code Quality: Super-Linter"
on:
  pull_request:
jobs:
  superlinter:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Lint Code
        uses: docker://github/super-linter:v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          VALIDATE_BASH: false
          VALIDATE_JSON: false
          VALIDATE_MD: false
          VALIDATE_TERRAFORM: false
          VALIDATE_YAML: false